name: 'setup-serverless'
description: 'Parameters used to create the Tencent Cloud Serverless distribution package'
inputs:
  app:
    description: 'Application name, default to component instance name'
    required: true
  component:
    description: 'Reference the name of component'
    required: true
  name:
    description: 'Name of the instance created by the component'
    required: true
  main:
    description: 'Start address'
    required: false
    default: 'main.js'
  lib:
    description: 'Project entry folder'
    required: true
  region:
    description: 'Application Deployment Area'
    required: true
  functionName:
    description: "Function name"
    required: true
  runtime:
    description: 'Nodejs version'
    required: true
  environment:
    description: 'Publishing environment'
    required: false
    default: 'release'
runs:
  using: 'node16'
  main: 'dist/index.js'
